package com.example.shopping_list.entity

import com.example.shopping_list.data.room.tables.BasketDB

object Plug {
    
//    val listBasket = listOf(
//        BasketDB(nameBasket = "box1", selected = false, fillBasket = false))

//    private fun BasketDB(nameBasket: String, selected: Boolean, fillBasket: Boolean): BasketDB {
//
//    }
//        BasketDB("box2", listOf(Product("box2Product0", Unit.L, 1.0),
//            Product("box2Product1", Unit.L, 1.0),
//            Product("box2Product2", Unit.L, 1.0),
//            Product("box2Product3", Unit.L, 1.0),
//            Product("box2Product4", Unit.L, 1.0),
//            Product("box2Product5", Unit.L, 1.0))),
//        BasketDB("box3", listOf(Product("box3Product0", Unit.L, 1.0),
//            Product("box3Product1", Unit.L, 1.0),
//            Product("box3Product2", Unit.L, 1.0),
//            Product("box3Product3", Unit.L, 1.0),
//            Product("box3Product4", Unit.L, 1.0),
//            Product("box3Product5", Unit.L, 1.0))),
//        BasketDB("box4", listOf(Product("box4Product0", Unit.L, 1.0),
//            Product("box4Product1", Unit.L, 1.0),
//            Product("box4Product2", Unit.L, 1.0),
//            Product("box4Product3", Unit.L, 1.0),
//            Product("box4Product4", Unit.L, 1.0),
//            Product("box4Product5", Unit.L, 1.0))),
//        BasketDB("box5", listOf(Product("box5Product0", Unit.L, 1.0),
//            Product("box5Product1", Unit.L, 1.0),
//            Product("box5Product2", Unit.L, 1.0),
//            Product("box5Product3", Unit.L, 1.0),
//            Product("box5Product4", Unit.L, 1.0),
//            Product("box5Product5", Unit.L, 1.0))),
//        BasketDB("box6", listOf(Product("box6Product0", Unit.L, 1.0),
//            Product("box6Product1", Unit.L, 1.0),
//            Product("box6Product2", Unit.L, 1.0),
//            Product("box6Product3", Unit.L, 1.0),
//            Product("box6Product4", Unit.L, 1.0),
//            Product("box6Product5", Unit.L, 1.0))),
//        BasketDB("box7", listOf(Product("box7Product0", Unit.L, 1.0),
//            Product("box7Product1", Unit.L, 1.0),
//            Product("box7Product2", Unit.L, 1.0),
//            Product("box7Product3", Unit.L, 1.0),
//            Product("box7Product4", Unit.L, 1.0),
//            Product("box7Product5", Unit.L, 1.0))),
//        BasketDB("box8", listOf(Product("box8Product0", Unit.L, 1.0),
//            Product("box8Product1", Unit.L, 1.0),
//            Product("box8Product2", Unit.L, 1.0),
//            Product("box8Product3", Unit.L, 1.0),
//            Product("box8Product4", Unit.L, 1.0),
//            Product("box8Product5", Unit.L, 1.0))),
//        BasketDB("box9", listOf(Product("box9Product0", Unit.L, 1.0),
//            Product("box9Product1", Unit.L, 1.0),
//            Product("box9Product2", Unit.L, 1.0),
//            Product("box9Product3", Unit.L, 1.0),
//            Product("box9Product4", Unit.L, 1.0),
//            Product("box9Product5", Unit.L, 1.0))),
//        BasketDB("box10", listOf(Product("box10Product0", Unit.L, 1.0),
//            Product("box10Product1", Unit.L, 1.0),
//            Product("box10Product2", Unit.L, 1.0),
//            Product("box10Product3", Unit.L, 1.0),
//            Product("box10Product4", Unit.L, 1.0),
//            Product("box10Product5", Unit.L, 1.0))),

//    val listProduct = listOf(
//        Product("box1Product0", Unit.L, 1.0),
//        Product("box1Product1", Unit.L, 1.0),
//        Product("box1Product2", Unit.G, 100.0),
//        Product("box1Product3", Unit.KG, 1.0),
//        Product("box1Product4", Unit.L, 1.0),
//        Product("box1Product5", Unit.L, 1.0),
//        Product("box2Product0", Unit.L, 1.0),
//        Product("box2Product1", Unit.L, 1.0),
//        Product("box2Product2", Unit.L, 1.0),
//        Product("box2Product3", Unit.L, 1.0),
//        Product("box2Product4", Unit.L, 1.0),
//        Product("box2Product5", Unit.L, 1.0),
//        Product("box3Product0", Unit.L, 1.0),
//        Product("box3Product1", Unit.L, 1.0),
//        Product("box3Product2", Unit.L, 1.0),
//        Product("box3Product3", Unit.L, 1.0),
//        Product("box3Product4", Unit.L, 1.0),
//        Product("box3Product5", Unit.L, 1.0),
//        Product("box4Product0", Unit.L, 1.0),
//        Product("box4Product1", Unit.L, 1.0),
//        Product("box4Product2", Unit.L, 1.0),
//        Product("box4Product3", Unit.L, 1.0),
//        Product("box4Product4", Unit.L, 1.0),
//        Product("box4Product5", Unit.L, 1.0),
//        Product("box5Product0", Unit.L, 1.0),
//        Product("box5Product1", Unit.L, 1.0),
//        Product("box5Product2", Unit.L, 1.0),
//        Product("box5Product3", Unit.L, 1.0),
//        Product("box5Product4", Unit.L, 1.0),
//        Product("box5Product5", Unit.L, 1.0),
//        Product("box6Product0", Unit.L, 1.0),
//        Product("box6Product1", Unit.L, 1.0),
//        Product("box6Product2", Unit.L, 1.0),
//        Product("box6Product3", Unit.L, 1.0),
//        Product("box6Product4", Unit.L, 1.0),
//        Product("box6Product5", Unit.L, 1.0),
//        Product("box7Product0", Unit.L, 1.0),
//        Product("box7Product1", Unit.L, 1.0),
//        Product("box7Product2", Unit.L, 1.0),
//        Product("box7Product3", Unit.L, 1.0),
//        Product("box7Product4", Unit.L, 1.0),
//        Product("box7Product5", Unit.L, 1.0),
//        Product("box8Product0", Unit.L, 1.0),
//        Product("box8Product1", Unit.L, 1.0),
//        Product("box8Product2", Unit.L, 1.0),
//        Product("box8Product3", Unit.L, 1.0),
//        Product("box8Product4", Unit.L, 1.0),
//        Product("box8Product5", Unit.L, 1.0),
//        Product("box9Product0", Unit.L, 1.0),
//        Product("box9Product1", Unit.L, 1.0),
//        Product("box9Product2", Unit.L, 1.0),
//        Product("box9Product3", Unit.L, 1.0),
//        Product("box9Product4", Unit.L, 1.0),
//        Product("box9Product5", Unit.L, 1.0),
//        Product("box10Product0", Unit.L, 1.0),
//        Product("box10Product1", Unit.L, 1.0),
//        Product("box10Product2", Unit.L, 1.0),
//        Product("box10Product3", Unit.L, 1.0),
//        Product("box10Product4", Unit.L, 1.0),
//        Product("box10Product5", Unit.L, 1.0),
//    )
}